# Metadata defining how notebooks in this repo are presented on the public app website.
- title: Feature guides
  description: General feature guides for Q-CTRL BOULDER OPAL
  items:
  - title: Noise-robust two-qubit gates
    description: Optimized dephasing-robust iSWAP
    filename: qctrl/noise-robust-two-qubit-gates.ipynb
  - title: Characterizing dynamically corrected gates
    description: Calculation of noise filtering properties in driven controls
    filename: qctrl/characterizing-dynamically-corrected-gates.ipynb
  - title: Characterizing dynamical decoupling sequences
    description: Calculation of filter functions for noise suppression in DD sequences
    filename: qctrl/characterizing-dynamical-decoupling-sequences.ipynb
