# Metadata defining how notebooks in this repo are presented on the public app website.
- title: Technology guides
  description: Targeted quantum technology guides for Q-CTRL BOULDER OPAL
  items:
  - title: Suppressing leakage errors
    description: Optimized gates for qubit subspaces within higher-dimensional manifolds
    filename: qctrl/suppressing-leakage-errors.ipynb
  - title: Superconducting qubits - single-qubit gates
    description: Optimized leakage-suppressing, band-limited, single-qubit Hadamard
    filename: qctrl/superconducting-qubits-single-qubit-gates.ipynb
  - title: Superconducting qubits - two-qubit gates
    description: Optimized iSWAP gate with suppression of leakage to spectator levels
    filename: qctrl/superconducting-qubits-two-qubit-gates.ipynb
  - title: Cold ion qubits - robust gates for atomic qubits
    description: Optimized dephasing-robust single-qubit Hadamard
    filename: qctrl/cold-ion-qubits-robust-gates-for-atomic-qubits.ipynb
  - title: Silicon qubits - ESR control for semiconducting spin qubits
    description: Dephasing-robust single-qubit Hadamard with bandwidth limits
    filename: qctrl/silicon-qubits-esr-control-for-semiconducting-spin-qubits.ipynb
  - title: Test SubGroup Lvl 2
    description: Dephasing-robust single-qubit Hadamard with bandwidth limits
    items:
      - title: Lvl 2 Item 1
        description: Optimized gates for qubit subspaces within higher-dimensional manifolds
        filename: qctrl/suppressing-leakage-errors.ipynb
      - title: Lvl 2 Item 2
        description: Optimized leakage-suppressing, band-limited, single-qubit Hadamard
        filename: qctrl/superconducting-qubits-single-qubit-gates.ipynb
      - title: Test SubGroup Lvl 3
        description: Dephasing-robust single-qubit Hadamard with bandwidth limits
        items:
          - title: Lvl 3 Item 1
            description: Optimized gates for qubit subspaces within higher-dimensional manifolds
            filename: qctrl/suppressing-leakage-errors.ipynb
          - title: Lvl 3 Item 2
            description: Optimized leakage-suppressing, band-limited, single-qubit Hadamard
            filename: qctrl/superconducting-qubits-single-qubit-gates.ipynb

- title: Feature guides
  description: General feature guides for Q-CTRL BOULDER OPAL
  items:
  - title: Noise-robust two-qubit gates
    description: Optimized dephasing-robust iSWAP
    filename: qctrl/noise-robust-two-qubit-gates.ipynb
  - title: Characterizing dynamically corrected gates
    description: Calculation of noise filtering properties in driven controls
    filename: qctrl/characterizing-dynamically-corrected-gates.ipynb
  - title: Characterizing dynamical decoupling sequences
    description: Calculation of filter functions for noise suppression in DD sequences
    filename: qctrl/characterizing-dynamical-decoupling-sequences.ipynb
